baseURL = 'https://docs.backlot.software/'
languageCode = 'en-us'
title = 'Backlot documentation'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10

[params.docs]
    darkMode    = true
    editPage    = true
    repoURL     = "https://github.com/backlot-software/backlot-software.github.io"
    repoBranch  = "main"
    lastMod     = true
    lastModRelative = true